apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.metadata.app }}
    tag: {{ .Values.metadata.tag }}
  name: helm-cluster-ip
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: 8111
    protocol: TCP
    targetPort: 8111
  selector:
    app: {{ .Values.metadata.app }}
    tag: {{ .Values.metadata.tag }}
  type: ClusterIP
