name: Build and Push

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: helm-test
  USERNAME: vertefra

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GitHub registry Login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push
        run: ./scripts/build-push.sh
